# Generated by Django 6.0.3 on 2026-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='ธนาคารกสิกรไทย', max_length=100, verbose_name='ชื่อธนาคาร')),
                ('bank_account_number', models.CharField(default='123-4-56789-0', max_length=50, verbose_name='เลขบัญชี')),
                ('bank_account_name', models.CharField(default='ชื่อของคุณ', max_length=100, verbose_name='ชื่อบัญชี')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่าข้อมูลร้านค้า',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
